name: Deploy NPM code

on:
   push:
     branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code    
          uses: actions/checkout@v3

        - name: npm lint
          run: npm i -g lint
          
    build: 
        needs: lint
        runs-on: ubuntu-latest
        
        steps: 
        - name: checkout code 
          uses: actions/checkout@v3
          
        - name: npm build
          run: npm run build

    test:
        needs: [ lint, build ]
        runs-on: ubuntu-latest

        steps: 
        - name: checkout code
          uses: actions/checkout@v3
          
        - name: run test 
          run: npm test 
    
